//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Grasp.Controller
{
    public class SalesServices
    {
        public virtual void RegisterSale()
        {
            //here we found that we are breaking the Creator Pattern:
            var myProduct = new Products { Code = "PROD 01" };
            var myDetail = new Details { Product = myProduct, Quantity = 40 };

            //Because "RegisterSale" is adding details to the Header, Is the header whose in charge of it.
            var myHeader = new Header { Details = new List<Details> { myDetail } };
        }
    }