//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Before.Grasp
{
    public class Details
    {
        public Products Product { get; set; }

        public int Quantity { get; set; }
    }

}