//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.HighCohesion
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CypherEncodedMd5 : IEncodable
	{
		public virtual string Encrypt()
		{
			throw new System.NotImplementedException();
		}

		public virtual string Decrypt()
		{
			throw new System.NotImplementedException();
		}

	}
}

