//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.HighCohesion
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class EmailNotification : INotifiable
	{
		public virtual bool Send()
		{
			throw new System.NotImplementedException();
		}

	}
}

