//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.HighCohesion
{
    public class RequestReported : IReportable
	{
		public void Create()
		{
			throw new System.NotImplementedException();
		}

	}
}

