//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{

	public class AuthenticationServices : IAuthenticationService
	{
		public virtual void Authenticate(Credential credential)
		{
			throw new System.NotImplementedException();
		}

	}
}

