//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{
	public class CryptoServices : ICryptoService
	{
		public virtual string Encode(string Password)
		{
			throw new System.NotImplementedException();
		}

	}
}

