//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{
	public interface IAuthenticationService 
	{
		void Authenticate(Credential credential);

	}
}

