//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{
	public class Logger : ILogger
	{
		public virtual void Initialize(Credential credential)
		{
			throw new System.NotImplementedException();
		}

        public void Finalizing()
        {
            throw new System.NotImplementedException();
        }

	}
}

