//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{
	public class NotifyServices : INotifyService
	{
		public virtual void NotifyInitSession(Credential credential)
		{
			throw new System.NotImplementedException();
		}

	}
}

