//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.LowCoupling
{
    using System.Web.Mvc;

    public class SecurityController : Controller
	{
        private readonly ILogger _logManager;
        private readonly ICryptoService _cryptoService;
        private readonly INotifyService _notifyService;
        private readonly IAuthenticationService _authenticationService;

        public SecurityController(ILogger serviceLogger, 
            ICryptoService serviceCrypto, 
            INotifyService serviceNotify, 
            IAuthenticationService serviceAuthentication)
        {
            _logManager = serviceLogger;
            _cryptoService = serviceCrypto;
            _notifyService = serviceNotify;
            _authenticationService = serviceAuthentication;
        }

        [HttpPost]
		public virtual void Authenticate(Credential credential)
		{
            _logManager.Initialize(credential);

            credential.Password = _cryptoService.Encode(credential.Password);

            _authenticationService.Authenticate(credential);

            _notifyService.NotifyInitSession(credential);

            _logManager.Finalizing();
		}

		

	}
}

