//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ExpertPattern
{
	using System.IO;

	public class FileAttachment
	{
		public string FilePath { get; set; }

		public bool FileExists()
		{
            return File.Exists(FilePath);
		}

	}
}

