//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ExpertPattern
{
    using System.Collections.Generic;

    public class Orders
	{
		public int Quantity { get; set; }

		public int Total { get; set; }

        public FileAttachment Attachment { get; set; }

        public ValidationResults ValidateInformation()
		{
            return new ValidationResults(GetRulesNotMatches());
		}

		public IEnumerable<string> GetRulesNotMatches()
		{
            if (Quantity <= 0)
                yield return "The Quantity of elements must be greater than 0.";
            if (Total >= 0)
                yield return "The Total must be greater than 0.";
            if (!Attachment.FileExists())
                yield return "The file you are trying to attach does not exists.";
        }

	}
}

