//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ExpertPattern
{
    using System.Collections.Generic;

    public class ValidationResults
	{
		public ValidationResults(IEnumerable<string> rulesNotMatched)
		{
		}

	}
}

