//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public abstract class Car : TransportVehicle
{
    private ITransportable _vehicle;
    ITransportable getInstance
	{
        get { return _vehicle; }
	}

}

