//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


/// <summary>
/// This is the Factory class
/// </summary>
public class Distributor
{
	public static IChoosable getChoosenTransport(ETransportationType choosenTransport)
	{
        IChoosable vehicle = null;
        
        switch (choosenTransport)
        {
            case ETransportationType.Convertible:
                {
                    vehicle = new ConvertibleCar();
                    break;
                }
            case ETransportationType.Coupe:
                {
                    vehicle = new CoupeCar();
                    break;
                }
            case ETransportationType.Sedan:
                {
                    vehicle = new SedanCar();
                    break;
                }
            case ETransportationType.Suv:
                {
                    vehicle = new SuvCar();
                    break;
                }
            case ETransportationType.Truck:
                {
                    vehicle = new TruckCar();
                    break;
                }
            case ETransportationType.Mountainbike:
                {
                    vehicle = new MountainBike();
                    break;
                }
        }
        return vehicle;
    }

}

