//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum ETransportationType : int
{
	Truck = 0,
	Suv = 1,
	Sedan = 2,
	Coupe = 3,
	Convertible = 4,
	Mountainbike = 5,
}
