//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Interface that contains the main properties for all type of transportation vehicles
/// </summary>
public interface ITransportable 
{
	string BrandName { get;set; }

	ETransportationType TypeOfTransportation { get;set; }

}

