//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace After.Grasp
{

    /// <summary>
    /// La clase Helper es muy genérica no tiene una funcionalidad clara y sus métodos no tienen relación entre sí, 
    /// como vemos esta clase se encarga de: cifrar, crear pdf, log, notificar, etc. 
    /// </summary>
	public class Helper
	{
		public virtual void Encode()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Decode(string encoded)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SendEmail()
		{
			throw new System.NotImplementedException();
		}

		public virtual void LogMessage()
		{
			throw new System.NotImplementedException();
		}

		public virtual void FileValidation()
		{
			throw new System.NotImplementedException();
		}

		public virtual void FileGeneration()
		{
			throw new System.NotImplementedException();
		}

	}
}

