//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BeforeExpert
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AttachFile
	{
		public virtual object Path
		{
			get;
			set;
		}

		public virtual object Mime
		{
			get;
			set;
		}

	}
}

