//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BeforeExpert
{
	public class FileAttachment
	{
		public string Path { get; set;}
	}
}

