//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BeforeExpert
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Order
	{
		public virtual AttachFile fileAttached
		{
			get;
			set;
		}

		/// <summary>
		/// Stores quantity
		/// </summary>
		public virtual int Cantidad
		{
			get;
			set;
		}

		public virtual int Total
		{
			get;
			set;
		}

		public virtual AttachFile AttachFile
		{
			get;
			set;
		}

		public virtual void ValidateInfo()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<string> GetRules()
		{
			throw new System.NotImplementedException();
		}

	}
}

