//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BeforeExpert
{
    using System.Collections.Generic;

    public class ValidationResults
	{
        public ValidationResults(IEnumerable<string> rulesNotAccomplished)
        {

        }
    }
}

