//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.Creator
{
    public class Details
	{
        public virtual Products Product { get; private set; }
        public int Quantity { get; private set; }

        public Details(Products product, int quantity)
        {
            Product = product;
            Quantity = quantity;
        }
    }
}

