//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.Creator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Headers
	{
        public Headers()
        {
            Detail = new List<Details>();
        }

        public IList<Details> Detail { get; private set; }

        public void AddDetail(string product, int qty)
        {
            var _detail = new Details(new Products() { ProductCode = product }, qty);
            Detail.Add(_detail);
        }

	}
}

