//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Grasp.Creator
{
	public class SalesAgentService
	{
		public virtual void RegisterSale()
		{
            var _header = new Headers();
            _header.AddDetail("Product 001", 40);
		}
	}
}

