//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LowCoupling.Before.Grasp
{
	public interface ILogger 
	{
		LogManager GetCurrentLogger();

		void Trace(string StepInfo);

	}
}

