//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LowCoupling.Before.Grasp
{	
	public class Logger : ILogger
	{
		public virtual LogManager GetCurrentLogger()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Trace(string StepInfo)
		{
			throw new System.NotImplementedException();
		}

	}
}

