//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace LowCoupling.Before.Grasp
{

    public class LogManager
    {
        internal static Logger GetCurrentLogger()
        {
            throw new NotImplementedException();
        }
    }
}

