//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LowCoupling.Before.Grasp
{
    using System;
    using System.Text;
    using System.Web.Mvc;
    using System.Security.Cryptography;
    using System.IO;
    using System.Data.SqlClient;
    using System.Net.Mail;

    public class SecurityController:Controller
	{
        private static Logger _logManager = LogManager.GetCurrentLogger();

        public byte[] IV { get; set; }
        public byte[] Key { get; set; }

        [HttpPost]
		public virtual void Authenticate(Credential credential)
		{
            //Log.
            var json = credential.ToJson();
            _logManager.Trace(string.Format("Inicio: {0} Data: {1}", DateTime.Now, json));
            //Log.

            //Cyphering
            byte[] inputBytes = Encoding.ASCII.GetBytes(credential.Password);
            byte[] encrypted;

            var crypt = new RijndaelManaged();
            using (var ms = new MemoryStream(inputBytes.Length))
            {
                using (var cryptStream = new CryptoStream(ms, crypt.CreateEncryptor(Key, IV),CryptoStreamMode.Write))
                {
                    //Code to encrypt.
                }
                encrypted = ms.ToArray();
            }
            credential.Password = Convert.ToBase64String(encrypted);

            //Cyphering

            //DB Stuffs

            using (var conection = new SqlConnection())
            {
                using (var cmd = new SqlCommand("command"))
                {
                    //Coding stuffs to DB.
                }
            }

            //DB Stuffs

            //Notification Stuffs
            MailMessage mail = new MailMessage("you@yourcompany.com", "user@hotmail.com");
            SmtpClient client = new SmtpClient();
            client.Host = "smtp.google.com";
            mail.Subject = "Inicio de sesion";
            mail.Body = " " ;
            client.Send(mail);
            //Notification Stuffs

            //Log.
            _logManager.Trace("Ended");
            //Log.
        }

    }
}

